service: gettogether

plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}

functions:
  getAllTogethers:
    handler: src/functions/getAllTogethers.handler
    events:
      - http:
          path: api/getAllTogethers
          method: get
    iamRoleStatements:
      -
        Effect: Allow
        Action: dynamodb:scan
        Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.getTogethersTableName}
    environment:
      getTogethersTableName: ${self:custom.getTogethersTableName}

  notifyOrganiser:
    handler: src/functions/notifyOrganiser.handler
    events:
      - sns: ${self:custom.joinGetTogetherSnsTopicName}

  joinGetTogether:
    handler: src/functions/joinGetTogether.handler
    events:
      - http:
          path: api/joinGetTogether
          method: post
    iamRoleStatements:
      -
        Effect: Allow
        Action: sns:publish
        Resource: ${self:custom.joinGetTogetherSnsTopic}
    environment:
      joinGetTogetherTopicArn: ${self:custom.joinGetTogetherSnsTopic}

resources:
  Resources:
    GetTogethersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.getTogethersTableName}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

custom:
  defaultRegion: eu-west-1
  defaultStage: dev${env:SLSUSER, ""}
  getTogethersTableName: ${ssm:/gettogethers/${self:provider.stage}/tableNameSecure~true}
  joinGetTogetherSnsTopicName: ${self:provider.stage}-joingettogethers
  joinGetTogetherSnsTopic: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.joinGetTogetherSnsTopicName}
